# Generated by Django 2.0.6 on 2019-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=200)),
                ('lastName', models.CharField(default='', max_length=200)),
                ('Email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('Image', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
